export {default as Bismillah} from './Bismillah.png'
export {default as fir} from './Group 92.svg'
export {default as Logo} from './Iqro-Quran.com.png'
export {default as sec} from './Vector (3).svg'
export {default as thir} from './Vector (4).svg'
export {default as burger} from './burger.svg'