export { default as more } from './more.svg';
export { default as next } from './next.svg';
export { default as close } from './close.svg';
export { default as playSecond } from './playSecond.svg';
export { default as pauseSecond } from './pouseSecond.svg';
export { default as previous } from './previous.svg';
export { default as Play } from './play.svg';
export { default as Pause } from './pause.svg';
export { default as Download } from './download.svg';
